name: remote ssh command test
on: 
  push:
    branches: [ main ]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PW }}
        port: ${{ secrets.REMOTE_PORT }}
        script: 
          cd ${{ secrets.REMOTE_PATH }}
          git pull origin main
